name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Крок 1: Отримання коду з репозиторію
      - name: Checkout repository
        uses: actions/checkout@v3

      # Крок 2: Встановлення Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Крок 3: Кешування залежностей
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Крок 4: Встановлення залежностей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov  # Додаємо pytest-cov для покриття коду

      # Крок 5: Запуск тестів з покриттям коду
      - name: Run tests with coverage
        run: |
          pytest --junitxml=test-results.xml --cov=main --cov-report=xml --cov-report=html

      # Крок 6: Збереження результатів тестів (JUnit)
      - name: Upload test results
        uses: actions/upload-artifact
        with:
          name: test-results
          path: test-results.xml

      # Крок 7: Збереження звіту про покриття коду (XML)
      - name: Upload coverage report (XML)
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-xml
          path: coverage.xml

      # Крок 8: Збереження звіту про покриття коду (HTML)
      - name: Upload coverage report (HTML)
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report-html
          path: htmlcov

      # Крок 9: Відображення результатів тестів
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: test-results.xml

      # Крок 10: Публікація покриття коду на Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml